### ISSUE TITLE
Strange behavior on singular version of pluralized acronyms

### ISSUE THREAD

**Issue by mdacosta** [blakeembrey/pluralize#137] opened 2019-11-08 12:19 UTC
Hi!

I noticed a strange behavior on how acronyms are handled.
When I try to get the singular version of `atms` (the case doesn't matter), or `iots`, everything works fine. It returns `atm` and `iot`.
But when I test with `skus`, it returns `skus`. 🤔 
Why is there a specific behavior for this case?

```
> pluralize.singular('atms');
'atm'
> pluralize.singular('hkjfbgs');
'hkjfbg'
> pluralize.singular('skus');
'skus'
```

**Comment by blakeembrey** [comment] 2019-11-13 03:49
@mdacosta Unfortunately `atms` works by accident and this library doesn't natively support acronyms. If you want acronym support, it's probably better in a different package - can you elaborate on your use case of acronyms so I can design a better solution?

**Comment by blakeembrey** [comment] 2019-11-13 03:50
Closing as a duplicate of https://github.com/blakeembrey/pluralize/issues/127 for now.

**Closed by blakeembrey** 2019-11-13 03:50 UTC

**Comment by mdacosta** [comment] 2019-11-13 10:03
This is not a duplicate of the issue you are mentionning.
The problem is different, and actually I don't know how you could possibly handle this uppercase acronym issue. For exemple the plural of "ATM" is "ATMs", but "USA" is already a plural (OK this is not a good example, but you see the point). It means that you should be aware of all the known acronyms (not to mention the invented ones) and handle them individually. This is clearly not manageable!

In my case, the problem comes from the rule which pluralize/singularize words which end by "us", like "bus" and its plural "buses".
"skus" (well known acronym for Stock Keeping Unit) is an exception in the way that this is the plural of "sku", but the library consider "skus" the singular version of "skuses", which is wrong.
And this is an issue for my use case explained here: https://github.com/strapi/strapi/issues/4482

**Comment by blakeembrey** [comment] 2019-11-13 13:08
Are you saying skus is a word and not an acronym? I’m a little confused, sorry. If it’s an acronym, I’d like to avoid handling it specifically - if I handle every variation of request I’ll end up with a dictionary, which isn’t the goal of this library. Maybe we can find a general rule to handle this so it’s not super specific?

**Comment by mdacosta** [comment] 2019-11-13 14:27
"SKU" is an acronym. You said "atms" works by accident, but it works, and I think everybody is fine with this. "sku" doesn't work only because of the rule on words ending by "us", and that's why I made a specific rule this very specific case.

I don't think you need to bother finding a way to handle acronyms written in uppercase ("ATM" -> "ATMs") like suggested in the [other issue](https://github.com/blakeembrey/pluralize/issues/127), because IMO it is nearly impossible to manage this properly without maintaining a dictionnary.
